version: 2

models:
- name: channels
  description: "channels"
  columns:
    - name: channel_id
      description: "The primary key for this table"
      tests:
        - unique
        - not_null
    - name: channel_name
      description: "channel name"
      tests:
        - unique
        - not_null
- name: customers
  description: "customers"
  columns:
    - name: customer_id
      description: "The primary key for this table"
      tests:
        - unique
        - not_null
    - name: first_name
      description: "first name of customer"
      tests:
        - not_null
    - name: last_name
      description: "last name of customer"
      tests:
        - not_null
    - name: email
      description: "email of customer"
- name: products
  description: "products"
  columns:
    - name: name
      description: "product name"
      tests:
        - not_null
    - name: city
      description: "product city"
      tests:
        - not_null
    - name: price
      description: "product price"
      tests:
        - not_null
    - name: product_id
      description: "The primary key for products"
      tests:
        - not_null
        - unique
- name: main
  description: "Transactions"
  columns:
    - name: transaction_id
      description: "The primary key for main"
      tests:
        - not_null
        - unique
    - name: customer_id
      description: "customer id references to customers"
      tests:
        - not_null
        - relationships:
            to: ref('customers')
            field: customer_id
    - name: product_id
      description: "product id references to products"
      tests:
        - not_null
        - relationships:
            to: ref('products')
            field: product_id
    - name: amount
      description: "transaction amount"
      tests:
        - not_null
    - name: qty
      description: "product quantity"
      tests:
        - not_null
    - name: channel_id
      description: "channel id references to channels"
      tests:
        - not_null
        - relationships:
              to: ref('channels')
              field: channel_id
    - name: bought_date
      description: "transaction date"
      tests:
        - not_null